## 导包

In [1]:
import numpy as np

In [2]:
np.__version__

'1.15.4'

### 列表创建方式

In [3]:
a1 = np.array([1,2,3])  # 创建了一维数组
a1

array([1, 2, 3])

In [4]:
a2 = np.array([
    [90, 80],
    [100,99],
    [80,100]
])  # 二维数组 -> 课程1、课程2的成绩
a2

array([[ 90,  80],
       [100,  99],
       [ 80, 100]])

In [6]:
# 注意： 数组里的每一个元素的类型都保持一致
# 如果列表中的数据类型不同时，则会按 int -> float -> string
a3 = np.array(['disen', 20, 90.5])
a3

array(['disen', '20', '90.5'], dtype='<U5')

### 数组对象的属性
- dtype   数组对象的类型
- ndim    数组的维度
- size    数组的成员总数量
- shape   数组的形状

In [9]:
display(a3.dtype)
display(a3.ndim)
display(a3.size)
display(a3.shape)
# 单元格输出结果是最后一行的code执行的结果，可以用display()或print()

dtype('<U5')

1

3

(3,)

In [12]:
display(a2.shape)
display(a2.size)

(3, 2)

6

In [13]:
a4 = np.array([199, 90.5, 77, 22.5])
a4

array([199. ,  90.5,  77. ,  22.5])

### 函数的创建方式 

In [53]:
a5 = np.ones(10, dtype=int)
a5

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [55]:
a6 = np.ones((10,5), dtype=int)
a6

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [57]:
a7 = np.eye(5, dtype=int, k=0)
a7

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [21]:
a8 = np.eye(5, dtype=int, k=1)
a8

array([[0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0]])

In [60]:
a9 = np.linspace(1, 10, num=10, dtype=int)
a9

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
# endpoint=True 表示包含最后一个值
a10 = np.linspace(1, 10, num=19, dtype=np.float)
a10

array([ 1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,
        6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [25]:
# 如果start不指定是从0
# 结果 不包含 end
all = np.arange(1, 11, step=1) # 1-10之间的数值，step步长
all

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
# numpy的数组对象的类是ndarray
a12 = np.full((3, 3), fill_value=5, dtype=np.int)
a12

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [27]:
type(a12)

numpy.ndarray

### 随机生成 ndarray

In [28]:
a13 = np.random.randint(10, 20, size=(3, 3))
a13

array([[10, 12, 10],
       [14, 15, 10],
       [11, 19, 10]])

In [66]:
# 生成0-100之间的10位同学的英语成绩
a14 = np.random.randint(0, 100, size=(10,))
a14

array([31, 74, 23, 35, 75, 55, 28, 34,  0,  0])

In [33]:
??np.random.randint

In [35]:
# 通过np.round()对ndarray数组中的元素进行四舍五入
np.round(np.random.uniform(100, size=10))

array([39., 64., 43., 26., 76., 82., 38., 32., 22., 98.])

In [36]:
np.random.randn(10)  # 从正态分布中随机选择10个数

array([ 1.23779453,  0.05041366,  0.17874888, -2.0701362 ,  0.09190486,
        0.82141445, -0.75737199,  0.33366735,  0.11896347,  1.59499909])

In [37]:
np.random.randn(3, 3)  # 从正态分布中获取3 * 3 二维形状的9个元素

array([[ 0.72654152,  0.72346942,  0.08977199],
       [-1.09137522,  0.54204162,  1.15180004],
       [ 0.86697623,  0.79492764,  0.81267567]])

In [43]:
np.random.randn(5, 3, 4)  # 5个三行四列的三维数组

array([[[ 0.28735749,  0.31548575, -1.3697689 , -1.0227391 ],
        [ 0.16507336,  0.30166726, -0.59029401, -0.49464448],
        [ 1.22424487,  0.63810448,  0.101651  , -1.19651639]],

       [[-0.68200658,  1.30440993, -0.21337086,  0.54638546],
        [ 0.03779601,  1.97646433, -0.62551986,  1.68201779],
        [-0.78774475,  0.03098123, -0.32875535,  0.10231143]],

       [[-0.8599324 ,  0.43760575,  0.38651859,  1.47411098],
        [ 0.22566314,  1.97941164, -0.35402916, -0.45950587],
        [ 0.53728618,  0.36094585, -0.15164052,  0.83781044]],

       [[-0.51910557, -0.24154307, -0.7891182 , -0.80487037],
        [-0.50734819,  0.62075671, -0.73357074,  0.34378135],
        [ 1.26590826, -0.50570215, -1.31307469,  0.28174991]],

       [[-0.8109465 ,  0.66970789, -0.85440439, -0.52054281],
        [ 0.56640182,  1.93454875,  0.68074769, -0.88148575],
        [ 0.74084529,  0.21669087, -0.5341582 , -0.68323031]]])

In [44]:
np.random.normal(size=(5, 3, 4))

array([[[-0.44595716, -0.56309238,  0.47196975, -1.32438471],
        [ 0.35582026,  0.85556359, -1.10777889, -0.09906378],
        [ 0.14934306,  1.39913463,  1.34854654, -0.01131515]],

       [[-0.51475521, -0.91547562, -1.03874455, -1.12241791],
        [ 0.66591594, -0.128719  , -0.75624148, -0.0830826 ],
        [ 0.22968837,  0.5371194 ,  0.6044384 ,  1.00271363]],

       [[ 0.12152347, -2.4857891 ,  0.08099273,  0.08995561],
        [-2.13341997,  0.38716996, -1.66827263,  0.89116238],
        [-0.77122865,  0.02163286, -0.14108019, -1.12536604]],

       [[-0.21211306,  1.43727318,  1.41017351,  0.04962023],
        [ 1.05520105,  0.46855026, -1.51516772, -0.61071944],
        [ 0.00842599, -1.21798183, -0.77879999,  0.16132722]],

       [[-1.41856587,  0.77989393, -0.23230065,  0.32734319],
        [-2.56046681, -0.00603316, -0.35017934,  0.12448254],
        [-0.0332509 ,  1.2139445 , -1.62595251,  0.86500034]]])

In [45]:
# 设置随机数的种子seed， 作用： 每次使用相同的随机种子， 每次生成的随机是相同的
np.random.seed(0)
np.random.randn(3, 3)

array([[ 1.76405235,  0.40015721,  0.97873798],
       [ 2.2408932 ,  1.86755799, -0.97727788],
       [ 0.95008842, -0.15135721, -0.10321885]])

In [47]:
np.random.seed(0)
np.random.normal(size=(3, 3))

array([[ 1.76405235,  0.40015721,  0.97873798],
       [ 2.2408932 ,  1.86755799, -0.97727788],
       [ 0.95008842, -0.15135721, -0.10321885]])

In [48]:
np.zeros((6, 6), dtype=int)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])