In [2]:
import numpy as np

In [3]:
# 生成10位同学的python，Django，scrapy三门课的成绩（0-150）的数组
scores = np.round(np.random.uniform(150, size=(10, 3)), 1)
scores

array([[ 70.5,  42.7, 107.9],
       [ 54.3,  99.8,  94.8],
       [140.6,  75.8,  96.1],
       [  3.6, 126.3, 120.1],
       [ 91.7,  55.6,  50. ],
       [148.1,  62.2, 144.6],
       [ 80.3,  99.3,  12.4],
       [ 53.9, 120.6,  39.5],
       [ 52.7, 118.6,  11.1],
       [ 71.3,  28.5,  23.7]])

In [5]:
scores.shape

(10, 3)

### 索引操作
- arr[index]
- arr[row_index, col_index]

In [6]:
# 查看第五位同学的所有课的成绩
five_score = scores[4]
five_score

array([91.7, 55.6, 50. ])

In [7]:
scores[4][1] # 第五位同学的第二门成绩， 索引从零开始

55.6

In [9]:
scores[4, 1]

55.6

### 索引切片
- arr[start:end:step] 行切，如果是一维数组，同list切片相同
- arr[:,start:end:step] 列切， 行索引部分是"："表示所有行，也可使用行切

In [10]:
# 查看前三位同学的所有成绩
scores[:3]

array([[ 70.5,  42.7, 107.9],
       [ 54.3,  99.8,  94.8],
       [140.6,  75.8,  96.1]])

In [12]:
# 查看所有同学的前两门课程的成绩
scores[:, :2]

array([[ 70.5,  42.7],
       [ 54.3,  99.8],
       [140.6,  75.8],
       [  3.6, 126.3],
       [ 91.7,  55.6],
       [148.1,  62.2],
       [ 80.3,  99.3],
       [ 53.9, 120.6],
       [ 52.7, 118.6],
       [ 71.3,  28.5]])

In [13]:
scores[:, [0, 2]]  # 查看所有人的第一门和第三门课程成绩

array([[ 70.5, 107.9],
       [ 54.3,  94.8],
       [140.6,  96.1],
       [  3.6, 120.1],
       [ 91.7,  50. ],
       [148.1, 144.6],
       [ 80.3,  12.4],
       [ 53.9,  39.5],
       [ 52.7,  11.1],
       [ 71.3,  23.7]])

In [16]:
# 查看第一位、第五位、第七位同学的第一门，第三门课程成绩
# 注意： ndarray不支持行和列同事局部选择
scores[[0, 4, 6]][:, [0,2]]

array([[ 70.5, 107.9],
       [ 91.7,  50. ],
       [ 80.3,  12.4]])

### ndarray的变形，reshape

In [17]:
heights = np.random.randint(155, 190, size=10)
heights

array([188, 164, 158, 161, 164, 159, 159, 156, 186, 169])

In [18]:
# 将十个元素大小的一维数组变形为三种形状：(2, 5), (5, 2), (10, 1)
heights.reshape((2, 5))

array([[188, 164, 158, 161, 164],
       [159, 159, 156, 186, 169]])

In [19]:
heights.reshape((5, 2))

array([[188, 164],
       [158, 161],
       [164, 159],
       [159, 156],
       [186, 169]])

In [20]:
heights.reshape((-1, 1)) # -1表示任意行数， 1 表示一列

array([[188],
       [164],
       [158],
       [161],
       [164],
       [159],
       [159],
       [156],
       [186],
       [169]])

### 数组对象的转置 T/transpose()

In [22]:
hh = heights.reshape((2, 5))
hh

array([[188, 164, 158, 161, 164],
       [159, 159, 156, 186, 169]])

In [25]:
hh = heights.reshape((2, 5))
hh.T

array([[188, 159],
       [164, 159],
       [158, 156],
       [161, 186],
       [164, 169]])

In [26]:
hh = heights.reshape((2, 5))
hh.transpose()

array([[188, 159],
       [164, 159],
       [158, 156],
       [161, 186],
       [164, 169]])

### ndarray的级联操作
- np.concatenate((arr1, arr2), axis=0)
- np.hstack((arr1, arr2))
- np.vstack((arr1, arr2))

In [28]:
a_height = np.random.randint(155, 190, size=(3, 2))
b_height = np.random.randint(155, 190, size=(3, 2))
c_height = np.random.randint(155, 190, size=(3, 2))
display(a_height, b_height, c_height)

array([[161, 156],
       [187, 189],
       [167, 189]])

array([[159, 165],
       [178, 166],
       [183, 163]])

array([[184, 161],
       [179, 163],
       [158, 176]])

In [33]:
# 将a和b的两个ndarray级联合并
# axis=1 将每一个一维数组中的元素提取，加到对应行上
np.concatenate((a_height, b_height), axis=1)  

array([[161, 156, 159, 165],
       [187, 189, 178, 166],
       [167, 189, 183, 163]])

In [60]:
# 将a和b的两个ndarray级联合并
# axis=0 将b中每一个一维数组提取，加到a所有数组之后
np.concatenate((a_height, b_height), axis=0)  

array([[161, 156],
       [187, 189],
       [167, 189],
       [159, 165],
       [178, 166],
       [183, 163]])

In [31]:
np.hstack((a_height, b_height))

array([[161, 156, 159, 165],
       [187, 189, 178, 166],
       [167, 189, 183, 163]])

In [32]:
np.vstack((a_height, b_height))

array([[161, 156],
       [187, 189],
       [167, 189],
       [159, 165],
       [178, 166],
       [183, 163]])

In [34]:
a =np.random.randint(100, size=(3, 2, 4))
b =np.random.randint(100, size=(3, 2, 4))
display(a ,b)

array([[[92, 71, 54, 89],
        [ 9, 37, 17, 48]],

       [[69, 30, 22,  4],
        [94, 36, 15, 78]],

       [[77, 12,  2, 87],
        [83, 66, 86, 62]]])

array([[[94, 39, 84, 31],
        [99, 34, 51, 86]],

       [[24, 96, 80, 39],
        [19, 55, 49, 53]],

       [[99, 15, 91, 30],
        [91,  9, 51, 58]]])

In [39]:
np.concatenate((a, b), axis=2)  #

array([[[92, 71, 54, 89, 94, 39, 84, 31],
        [ 9, 37, 17, 48, 99, 34, 51, 86]],

       [[69, 30, 22,  4, 24, 96, 80, 39],
        [94, 36, 15, 78, 19, 55, 49, 53]],

       [[77, 12,  2, 87, 99, 15, 91, 30],
        [83, 66, 86, 62, 91,  9, 51, 58]]])

### ndarray的切分 split

In [40]:
c = np.concatenate((a, b))
c.shape

(6, 2, 4)

In [42]:
d = c.reshape((-1 ,4))
d

array([[92, 71, 54, 89],
       [ 9, 37, 17, 48],
       [69, 30, 22,  4],
       [94, 36, 15, 78],
       [77, 12,  2, 87],
       [83, 66, 86, 62],
       [94, 39, 84, 31],
       [99, 34, 51, 86],
       [24, 96, 80, 39],
       [19, 55, 49, 53],
       [99, 15, 91, 30],
       [91,  9, 51, 58]])

In [43]:
# 将c的ndarray从第四个开始分割出两个ndarray
np.split(d, 6) # 如果 参数是 int 数值，表示平均分多少个数组

[array([[92, 71, 54, 89],
        [ 9, 37, 17, 48]]), array([[69, 30, 22,  4],
        [94, 36, 15, 78]]), array([[77, 12,  2, 87],
        [83, 66, 86, 62]]), array([[94, 39, 84, 31],
        [99, 34, 51, 86]]), array([[24, 96, 80, 39],
        [19, 55, 49, 53]]), array([[99, 15, 91, 30],
        [91,  9, 51, 58]])]

In [47]:
# 如果切割indices_or_secions的参数是[]列表类型，表示从那一部分上分割
np.split(d, [3])  

[array([[92, 71, 54, 89],
        [ 9, 37, 17, 48],
        [69, 30, 22,  4]]), array([[94, 36, 15, 78],
        [77, 12,  2, 87],
        [83, 66, 86, 62],
        [94, 39, 84, 31],
        [99, 34, 51, 86],
        [24, 96, 80, 39],
        [19, 55, 49, 53],
        [99, 15, 91, 30],
        [91,  9, 51, 58]])]

In [49]:
# axis=0 纵向切割， 从维度的最外层看所有一维数组
np.split(d, [3, 5], axis=0) # 将下标索引为3,4,5分割为一个ndarray

[array([[92, 71, 54, 89],
        [ 9, 37, 17, 48],
        [69, 30, 22,  4]]), array([[94, 36, 15, 78],
        [77, 12,  2, 87]]), array([[83, 66, 86, 62],
        [94, 39, 84, 31],
        [99, 34, 51, 86],
        [24, 96, 80, 39],
        [19, 55, 49, 53],
        [99, 15, 91, 30],
        [91,  9, 51, 58]])]

In [50]:
# 将 d 的数组的第三列切割为一个ndarray
np.split(d, [2, 3], axis=1)

[array([[92, 71],
        [ 9, 37],
        [69, 30],
        [94, 36],
        [77, 12],
        [83, 66],
        [94, 39],
        [99, 34],
        [24, 96],
        [19, 55],
        [99, 15],
        [91,  9]]), array([[54],
        [17],
        [22],
        [15],
        [ 2],
        [86],
        [84],
        [51],
        [80],
        [49],
        [91],
        [51]]), array([[89],
        [48],
        [ 4],
        [78],
        [87],
        [62],
        [31],
        [86],
        [39],
        [53],
        [30],
        [58]])]

### nadrray的copy副本

In [51]:
d2 = d.copy()
d2

array([[92, 71, 54, 89],
       [ 9, 37, 17, 48],
       [69, 30, 22,  4],
       [94, 36, 15, 78],
       [77, 12,  2, 87],
       [83, 66, 86, 62],
       [94, 39, 84, 31],
       [99, 34, 51, 86],
       [24, 96, 80, 39],
       [19, 55, 49, 53],
       [99, 15, 91, 30],
       [91,  9, 51, 58]])

In [52]:
d2[0 , 0] = 100
d2

array([[100,  71,  54,  89],
       [  9,  37,  17,  48],
       [ 69,  30,  22,   4],
       [ 94,  36,  15,  78],
       [ 77,  12,   2,  87],
       [ 83,  66,  86,  62],
       [ 94,  39,  84,  31],
       [ 99,  34,  51,  86],
       [ 24,  96,  80,  39],
       [ 19,  55,  49,  53],
       [ 99,  15,  91,  30],
       [ 91,   9,  51,  58]])

In [53]:
weights = np.random.randint(50, 120, size=(5, 3))
weights

array([[103,  63,  91],
       [ 98,  91, 112],
       [ 54,  98,  83],
       [109,  81,  90],
       [ 59,  73,  67]])

In [57]:
weights_copy = weights.copy()  # 深度copy
weights[-1, -1] = 100
weights

array([[103,  63,  91],
       [ 98,  91, 112],
       [ 54,  98,  83],
       [109,  81,  90],
       [ 59, 100, 100]])

In [58]:
weights_copy

array([[103,  63,  91],
       [ 98,  91, 112],
       [ 54,  98,  83],
       [109,  81,  90],
       [ 59, 100,  67]])