### ndarray的基本算数运算

In [1]:
import numpy as np

In [2]:
# 创建一位同学的三门课程
a_score = np.random.randint(150, size=3)
a_score

array([ 22, 127,  54])

In [5]:
a_score += 10  # ，每门课都加上10分、
a_score

array([ 52, 157,  84])

In [6]:
a_score[1] = 60
a_score

array([52, 60, 84])

In [7]:
# 将最后一门课程的成绩，修改为平均成绩+10分
a_score[-1] = a_score.mean() + 10
a_score

array([52, 60, 75])

In [8]:
# 设置第二门课程的成绩为None，表示没考试
a_score[1] = 0  # 数值中不能出现None -> pandas.nan
a_score

array([52,  0, 75])

In [10]:
# 创建5位同学的H5,java,texting和python四门课的成绩
score = np.random.randint(100, size=(5, 4))
score

array([[35, 36, 53, 47],
       [30, 53,  2, 22],
       [13, 63, 76, 55],
       [21, 76, 75, 72],
       [82, 14, 23, 46]])

In [11]:
# 第三位同学的所有课程的成绩都加上10分
score[2] += 10
score

array([[35, 36, 53, 47],
       [30, 53,  2, 22],
       [23, 73, 86, 65],
       [21, 76, 75, 72],
       [82, 14, 23, 46]])

In [12]:
score *= 2   # 所有人的每一门课程都乘以2
score

array([[ 70,  72, 106,  94],
       [ 60, 106,   4,  44],
       [ 46, 146, 172, 130],
       [ 42, 152, 150, 144],
       [164,  28,  46,  92]])

In [13]:
# 将所有人的第一门课程和最后一门课程的成绩都设为0
score[:, [0, -1]] = 0
score

array([[  0,  72, 106,   0],
       [  0, 106,   4,   0],
       [  0, 146, 172,   0],
       [  0, 152, 150,   0],
       [  0,  28,  46,   0]])

### ndarray特有的广播机制
- 为缺失的维度自动补1
- 使用现有元素填充空缺的值

In [14]:
a = np.array([1, 2, 3])  # [1, 2, 3]
a += 10   # 10 -> [10, 10, 10]
a

array([11, 12, 13])

In [15]:
a = np.array([1, 2, 3])
a += np.array([10, 10, 10])
a

array([11, 12, 13])

In [16]:
b = np.array([[1, 2], [3, 4]])
b += 15  # 15 -> [[15, 15], [15, 15]]
b

array([[16, 17],
       [18, 19]])

In [17]:
b = np.array([[1, 2], [3, 4]])
b += np.array([[15, 15], [15, 15]])
b

array([[16, 17],
       [18, 19]])

In [19]:
c = np.array([[5, 7], [10, 20]])
b += c
b

array([[21, 24],
       [28, 39]])

In [20]:
d = np.array([8 ,9])
b -= d
b

array([[13, 15],
       [20, 30]])

### 矩阵积的操作
- np.dot()

In [21]:
# 前提条件： 前面的数组的列数和后面数组的行数保持一致
a = np.array([[1, 3, 5],
              [2, 4, 6]])
b = np.array([[10, 20, 30], 
              [1, 2, 3],
              [4, 5, 6]])
np.dot(a, b)

array([[ 33,  51,  69],
       [ 48,  78, 108]])