### 最大值、最小值和平均值

In [1]:
import numpy as np

In [3]:
# 6个城市5种水果
price = np.round(np.random.uniform(1, 10, size=(6, 5)), 1)
price

array([[3.4, 8. , 2.4, 7. , 3.9],
       [4.7, 3.5, 7.1, 7.6, 8. ],
       [8.1, 4. , 8.4, 4. , 1.5],
       [6.8, 7.9, 3.5, 6.4, 4. ],
       [6.3, 9.8, 6.1, 7.4, 6. ],
       [5.7, 5.5, 9. , 5.6, 2.6]])

#### # 分别查看每个城市的水果总价、平均、最高、最低

In [4]:
price.sum(axis=1)  # 每个城市的水果总价

array([24.7, 30.9, 26. , 28.6, 35.6, 28.4])

In [6]:
price.mean(axis=1)  # 每个城市的平均价

array([4.94, 6.18, 5.2 , 5.72, 7.12, 5.68])

In [7]:
price.max(axis=1)

array([8. , 8. , 8.4, 7.9, 9.8, 9. ])

In [8]:
price.min(axis=1)

array([2.4, 3.5, 1.5, 3.5, 6. , 2.6])

#### 查看所有城市的水果总价、平均、最高、最低

In [9]:
price.sum(axis=0)  # 未完待续

array([35. , 38.7, 36.5, 38. , 26. ])

###  读取excel的文件，pandas库

In [10]:
import pandas as pd

In [11]:
heights = pd. read_excel('heights.xlsx')
heights

height  weight
0     180      70
1     185      75
2     155      50
3     165      65
4     190     110
5     186     105

In [12]:
heights.values # ndarray

array([[180,  70],
       [185,  75],
       [155,  50],
       [165,  65],
       [190, 110],
       [186, 105]], dtype=int64)

In [13]:
heights.values.mean(axis=0)

array([176.83333333,  79.16666667])