In [1]:
import numpy as np

In [4]:
# 创建10位员工的基本工资、绩效和奖金的信息
salary = np.random.randint(10000,30000, size=(10, 1))
jx = np.random.randint(1000, 3000, size=(10 ,1))
jj = np.random.randint(500, 1500, size=(10, 1))
persons = np.hstack((np.hstack((salary, jx)), jj))
persons

array([[12384,  1078,   557],
       [24984,  2842,   701],
       [25535,  2907,  1009],
       [19205,  1470,   577],
       [20113,  2263,  1356],
       [18411,  2916,   554],
       [14485,  1126,  1145],
       [21606,  1865,  1393],
       [14606,  1222,  1427],
       [20195,  2582,  1342]])

In [5]:
# 使用np.sort()函数，类似于内置的sorted()函数，会返回排序后的结果
np.sort(persons, axis=0)  # 每一列的不同行数值排序

array([[12384,  1078,   554],
       [14485,  1126,   557],
       [14606,  1222,   577],
       [18411,  1470,   701],
       [19205,  1865,  1009],
       [20113,  2263,  1145],
       [20195,  2582,  1342],
       [21606,  2842,  1356],
       [24984,  2907,  1393],
       [25535,  2916,  1427]])

In [6]:
np.sort(persons, axis=1)  # 每一行，按列值排序

array([[  557,  1078, 12384],
       [  701,  2842, 24984],
       [ 1009,  2907, 25535],
       [  577,  1470, 19205],
       [ 1356,  2263, 20113],
       [  554,  2916, 18411],
       [ 1126,  1145, 14485],
       [ 1393,  1865, 21606],
       [ 1222,  1427, 14606],
       [ 1342,  2582, 20195]])

In [8]:
persons_copy = persons.copy()
persons_copy.sort(axis=0)  # 类似于list.sort()函数，直接对数组进行排序

In [9]:
persons_copy

array([[12384,  1078,   554],
       [14485,  1126,   557],
       [14606,  1222,   577],
       [18411,  1470,   701],
       [19205,  1865,  1009],
       [20113,  2263,  1145],
       [20195,  2582,  1342],
       [21606,  2842,  1356],
       [24984,  2907,  1393],
       [25535,  2916,  1427]])

In [11]:
np.partition(persons, 2, axis=0)  # 部分排序，只排到前两个

array([[12384,  1078,   554],
       [14485,  1126,   557],
       [14606,  1222,   577],
       [19205,  1470,  1009],
       [20113,  2263,  1356],
       [18411,  2916,   701],
       [24984,  2842,  1145],
       [21606,  1865,  1393],
       [25535,  2907,  1427],
       [20195,  2582,  1342]])

In [13]:
np.partition(persons, -2, axis=0)[-2:]

array([[24984,  2907,  1393],
       [25535,  2916,  1427]])